### ISSUE TITLE
how to?

### ISSUE THREAD

**Issue by YGwen** [Kelvin-Chen/seedbox#1]
Works great you sir are a true hero.

**Comment by Kelvin-Chen** [comment]
Hello,
To use it you have to first install docker and docker-compose. You can find the instructions for that [here](https://docs.docker.com/compose/install/).
After that just clone the repository and enter it.
```bash
git clone https://github.com/Kelvin-Chen/seedbox.git
cd seedbox
```
Finally, just pull the images with docker-compose and start everything.
```bash
docker-compose pull
docker-compose up -d
```
Hope this helps!

**Comment by YGwen** [comment]
Eventually I also had to : docker-compose migrate-to-labels
Works perfectly in the end, thank you very much, keep up the good work :)
